// Copies contract ABIs from the Foundry build (../contracts/out) into
// src/shared/abi.ts, so the Worker and the client share one source.
import { readFileSync, writeFileSync } from "node:fs";

const names = ["NokorPass", "NokorRegistry", "NokorMoney", "NokorAccess", "NokorPoint"];
let out = "// Generated by scripts/extract-abi.mjs from ../contracts/out. Do not edit.\n\n";
for (const n of names) {
  const j = JSON.parse(readFileSync(new URL(`../../contracts/out/${n}.sol/${n}.json`, import.meta.url)));
  out += `export const ${n}Abi = ${JSON.stringify(j.abi, null, 0)} as const;\n\n`;
}
writeFileSync(new URL("../src/shared/abi.ts", import.meta.url), out);
console.log("wrote src/shared/abi.ts");
